### PR TITLE
Add support for MinGW-w64

### PR DESCRIPTION
**Pull request by BobSmun**
- Does not add support for ASSIMP
- When catching exceptions from runtime compiled code, the exception address not captured
- libfreetype.a compiled without debug info using MinGW-w64 i686-5.3.0-win32-dwarf-rt_v4-rev0
- libfreetypex64.a compiled without debug info using MinGW-w64 x86_64-5.3.0-win32-seh-rt_v4-rev0

Compilers Tested:
- MinGW-w64 i686-4.9.1-win32-dwarf-rt_v3-rev1
- MinGW-w64 i686-5.3.0-win32-dwarf-rt_v4-rev0
- MinGW-w64 x86_64-4.9.1-win32-seh-rt_v3-rev1
- MinGW-w64 x86_64-5.3.0-win32-seh-rt_v4-rev0
- VS 2015 x86 & x86_64

### CODE REVIEW

**Comment by BobSmun** [comment]
This should address #60

**Comment by dougbinks** [comment]
Thanks! This will take me a bit of time to check out.

**Comment by dougbinks** [comment]
Many thanks for all the work! This is a fairly major change to the Windows runtime compiler, and it breaks the existing Visual Studio project files provided (i.e. ones not generated with cmake).

Though these issues can be resolved, after investigating more about MinGW, I'm not very happy about the idea of supporting this myself - there are free versions of Visual Studio available and MinGW doesn't fully support POSIX functionality, nor does it have that as it's aim.

I think the best option here would be that I add a link to your fork as a MinGW port. To make it easier to keep the two in sync I would revert the changes to Compiler_PlatformWIndows.cpp, but as it's your fork that decision is up to you.

Once again I think it's great that you've done this, but I am concerned I would not be able to support MinGW.

**Comment by BobSmun** [comment]
My next suggestion would have actually been to remove the included project files, in favour of using CMake to generate them as required.

As there appears to be a relatively low demand for this port, I don't think there is much urgency in merging the changes. In that case, it indeed would be best to revert the changes to Compiler_PlatformWindows.cpp to allow easier synchronisation between the two repositories. These changes were made primarily as an attempt to avoid code duplication and keep the similarities between VS and MinGW in sync, but are not strictly necessary.

As for VS, granted there are free versions of VS available, however, for me at least, it wasn't about the price tag. Notably, VS has been quite slow in adopting the newer C++ standards and although VS2015 made huge progress in this regard, it is currently still behind. 


In any case, the code is available via the fork. Whether or not it gets merged to the core repository, is your choice.

**Comment by dougbinks** [comment]
Some of people who use RCC++ don't use cmake, and cmake's VS generation has the awkward property of not combining 32bit and 64bit builds under one solution so removing them is not something I'd want to do.

As for code duplication I understand the intent but think it would make things harder for me (see http://www.sandimetz.com/blog/2016/1/20/the-wrong-abstraction for some thoughts on abstraction vs duplication).

Point take about VS standard adoption. Hopefully their work with Clang may help here in future.

Would it be OK for me to add a note and link in the readme about your fork, and perhaps write a short blog post to announce you've got this working?

**Comment by BobSmun** [comment]
Yeah, feel free to point towards the fork.

I'll also revert Compiler_PlatformWindows.cpp, when I get the chance.

**Comment by dougbinks** [comment]
Somewhat belatedly I've just added a note in the readme with a link to your port, thanks!

**Pull request closed without merging**
