### PR TITLE
Fixed compilation of same file multiple times due to storing both relative and absolute paths

### PR DESCRIPTION
**Pull request by MomoDeve**
I am building RuntimeCompiledCPlusPlus with CMake on Windows. `__FILE__` macro, which is used inside `REGISTERCLASS` macro, produces relative path to the building directory (so if I have `runtime.cpp` in the project root directory, and build files are written to the `out/build/x64-Debug` directory, `__FILE__` macro for `runtime.cpp` will be equal to `..\..\..\runtime.cpp`.

The problems arise when I try to recompile this file at runtime. In that case `__FILE__` is equal to the **absolute** path of `runtime.cpp`: `D:\repos\RuntimeCppTest\runtime.cpp`, so after recompilation the project starts tracking both relative and absolute paths not checking if they are actually referencing the same file.

This leads to the errors after first recompilation. Below you can see output when `runtime.cpp` is recompiled in runtime for the first time:
```
[info]: FileChangeNotifier triggered recompile with changes to:
[info]:     File ..\..\..\runtime.cpp
[info]: Compiling...
[info]: cl /nologo /Z7 /FC /MDd /LDd /Od   /MP /Fo"D:\repos\RuntimeCppTest\out\build\x64-Clang-Debug\Runtime\DEBUG_DEBUG\\" /D WIN32 /EHa /FeC:\Users\Momo\AppData\Local\Temp\72D4.tmp  /I "..\..\..\runtimecompiledcplusplus\aurora\runtimeobjectsystem" /I "..\..\..\runtimecompiledcplusplus\aurora\RuntimeCompiler" /I "D:/repos/RuntimeCppTest/RuntimeCompiledCPlusPlus/Aurora"  "..\..\..\runtime.cpp" "d:\repos\runtimecpptest\out\build\x64-clang-debug\runtime\debug_debug\objectinterfacepermodulesource.obj"
echo [info]:
[info]: **********************************************************************
[info]: ** Visual Studio 2019 Developer Command Prompt v16.7.5
[info]: ** Copyright (c) 2020 Microsoft Corporation
[info]: **********************************************************************
tick
[info]: [vcvarsall.bat] Environment initialized for: 'x86_x64'
[info]:
[info]: runtime.cpp
tick
[info]:    Creating library C:\Users\Momo\AppData\Local\Temp\72D4.lib and object C:\Users\Momo\AppData\Local\Temp\72D4.exp
[info]:
[info]: [RuntimeCompiler] Complete
[info]: [info]:
[info]: Compilation Succeeded
[info]: Serializing out from 1 old constructors...
[info]: Swapping in and creating objects for 1 new constructors...
[info]: Serialising in...
[info]: Auto Constructing Singletons...
[info]: Initialising and testing new serialisation...
[info]: Object swap completed
```
And here you can see the output when `runtime.cpp` is recompiled for the second time (and etc). VS compiler cannot write to `runtime.obj` more than once, as it already participates in build. As a result, it fails to produce a library:
```
[info]: FileChangeNotifier triggered recompile with changes to:
[info]:     File ..\..\..\runtime.cpp
[info]:     File d:\repos\runtimecpptest\runtime.cpp
[info]: Compiling...
[info]: cl /nologo /Z7 /FC /MDd /LDd /Od   /MP /Fo"D:\repos\RuntimeCppTest\out\build\x64-Clang-Debug\Runtime\DEBUG_DEBUG\\" /D WIN32 /EHa /FeC:\Users\Momo\AppData\Local\Temp\92C0.tmp  /I "..\..\..\runtimecompiledcplusplus\aurora\runtimeobjectsystem" /I "..\..\..\runtimecompiledcplusplus\aurora\RuntimeCompiler" /I "D:/repos/RuntimeCppTest/RuntimeCompiledCPlusPlus/Aurora"  "..\..\..\runtime.cpp" "d:\repos\runtimecpptest\runtime.cpp" "d:\repos\runtimecpptest\out\build\x64-clang-debug\runtime\debug_debug\objectinterfacepermodulesource.obj"
echo [info]:
[info]: **********************************************************************
[info]: ** Visual Studio 2019 Developer Command Prompt v16.7.5
[info]: ** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
tick
[info]: [vcvarsall.bat] Environment initialized for: 'x86_x64'
[info]:
[info]: runtime.cpp
[info]: runtime.cpp
[error]: d:\repos\runtimecpptest\runtime.cpp : fatal error C1083: Cannot open compiler generated file: 'D:\repos\RuntimeCppTest\out\build\x64-Clang-Debug\Runtime\DEBUG_DEBUG\runtime.obj': Permission denied
[info]: cl : Command line error D8040 : [info]: error creating or communicating with child process
[info]:
[info]: [RuntimeCompiler] Complete
[info]: [info]:
[error]: Failed to load module C:\Users\Momo\AppData\Local\Temp\92C0.tmp
```
My solution for that is to check if the filepath provided by `__FILE__` is relative. If so, we need to make it absolute by concatenating it with current working directory. With this fix everything seems to work (at least on my machine).

### CODE REVIEW

**Comment by dougbinks** [comment]
Before accepting this PR I'd like to check wether the current solutions work. Check out the Project Setup:
https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/wiki/Integrating-to-your-own-codebase

With Visual Studio the "/FC" options is required to set absolute paths, does Clang for Windows have a similar option?

Alternatively, you can configure the define ```COMPILE_PATH``` to be set to the path required.

I don't think using the current working directory will work in general, since the relative build path and the executable or working path will likely be different. However it might make a good backup option to add this in RuntimeObjectSystem::FindFile().

**Comment by dougbinks** [comment]
Note that it looks like cl-clang foes not support the "/FC" option, and just ignores it. So the fix would be to set the ```COMPILE_PATH``` to the root directory required.

I'll investigate the automatic relative file path fix later, though I think the place to put this is in the FindFile() function in case the relative path itself works.

**Comment by MomoDeve** [comment]
`COMPILE_PATH` macro indeed works, but to be honest I dislike this solution because it forces library user to check if `__FILE__` produces relative path and also make sure that `COMPILE_PATH`  is written in the native form (for example CMake always uses `/` as separators for its path variables, but windows separator is `\`)

if I ignore this fact, I get the following paths (first procuces with `COMPILE_PATH`), and they are considered different (for example, [here](https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/blob/master/Aurora/RuntimeObjectSystem/RuntimeObjectSystem.cpp#L140))

| d:/repos/runtimecpptest\runtime.cpp |
|---------------------------------------|
| d:\repos\runtimecpptest\runtime.cpp |

maybe the real problem here is that very often paths are compared as strings and not checked if they are referencing the same file

**Comment by dougbinks** [comment]
The ```COMPILE_PATH``` is needed because not everyone will have the current directory set to the same path as the compilers relative path.

I am in favour of adding a fallback in FindFile() to add the current directory plus the relative path if relative is found, and can look into that shortly.

It looks like I also need to ensure that paths are changed to OS canonical form.

**Comment by MomoDeve** [comment]
maybe convert filepath to canonical form [here](https://github.com/RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus/blob/master/Aurora/RuntimeObjectSystem/ObjectInterfacePerModule.h#L112)? This requires including `FileSystemUtils.h` from RuntimeCompiler though.
```cpp
auto path = FileSystemUtils::Path(COMPILE_PATH + m_FileName);
path = DelimitersToOSDefault().GetCleanPath();
path.ToOSCanonicalCase();
m_FileName = path.m_string;
```

**Comment by dougbinks** [comment]
That's a good place for me to do it, but I would create a function in ```ObjectInterfacePerModuleSource.cpp``` so ```FileSystemUtils.h``` doesn't need get included everywhere.

I should be able to do this fairly soon.

**Comment by MomoDeve** [comment]
Cool. I will be really glad if filepaths work the same way as from std::filesystem. In stdlib paths mostly do not care about `\` `/` problem and also nicely concates. For example, `absolute path / relative = absolute`, `absolute path A / absolute path B = absolute path B`

**Comment by MomoDeve** [comment]
Cool! When can I expect the changes to be in master branch?

**Comment by dougbinks** [comment]
I've merged the "Improved constructor file paths and relative path support when using" commit along with your PR for optimization, and will look into the relative path improvements over the weekend - there is a little complexity in ensuring this doesn't add significant work for projects (like mine) which have lots of RCC++ files.

**Comment by MomoDeve** [comment]
Yeah, everything seems to work now. Thanks, so now I can close this PR

**Comment by dougbinks** [comment]
Thanks for this and other PRs, I'll look into adding Clang to my test suite at some point soon.

I'll still investigate the automatic relative path handling -  I've opened #115 for this.

**Comment by dougbinks** [comment]
I've closed #115 with improvements for FindFile when a relative path is used.

**Pull request closed without merging**
