### PR TITLE
use a better COMPILE_PATH definition.

### PR DESCRIPTION
**Pull request by moodyhunter**
the original `$(pwd)` syntax only works for `Unix MakeFile`, but not `Ninja`.

### CODE REVIEW

**Comment by dougbinks** [comment]
Thanks for the find and PR. I'll check this over on all platforms soon.

Meanwhile I note we currently have `cmake_minimum_required(VERSION 2.8)` but `add_compile_definitions` requires `3.12`, so we should update that before pulling. I'll do this before testing if you don't.

**Comment by moodyhunter** [comment]
Oops sorry, I didn't check for the version compatibility. 

The main point in this PR is to substitute the `$(PWD)` with `${CMAKE_BINARY_DIR}`.

There're two options:
- Upgrade the minimum cmake required version or,
- Use something like `Set(CMAKE_CXX_FLAGS  "-DCOMPILE_PATH=\"\\\"${CMAKE_BINARY_DIR}\\\"\"")` for backward compatibility.

I'd prefer the first one.

**Comment by dougbinks** [comment]
I think 3.12 is sufficiently old now that updating to that version is fine.

**Comment by dougbinks** [comment]
This took some time to test - the updated version of cmake required caused a cascade of issues resulting in me needing to uninstall and re-install macports then reinstall the dependencies.

**Comment by dougbinks** [comment]
All merged, many thanks for the PR !

**Comment by moodyhunter** [comment]
all my pleasure!

**Pull request merged**
